In [5]:
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.pipeline import Pipeline

In [6]:
rawDataFrame = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
rawDataFrame

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [7]:
rawDataFrame.drop(columns=["id", "Unnamed: 32"], inplace=True)
rawDataFrame.sample(5)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
181,M,21.09,26.57,142.70,1311.0,0.11410,0.28320,0.24870,0.14960,0.2395,...,26.68,33.48,176.50,2089.0,0.1491,0.7584,0.67800,0.29030,0.4098,0.12840
227,B,15.00,15.51,97.45,684.5,0.08371,0.10960,0.06505,0.03780,0.1881,...,16.41,19.31,114.20,808.2,0.1136,0.3627,0.34020,0.13790,0.2954,0.08362
478,B,11.49,14.59,73.99,404.9,0.10460,0.08228,0.05308,0.01969,0.1779,...,12.40,21.90,82.04,467.6,0.1352,0.2010,0.25960,0.07431,0.2941,0.09180
518,B,12.88,18.22,84.45,493.1,0.12180,0.16610,0.04825,0.05303,0.1709,...,15.05,24.37,99.31,674.7,0.1456,0.2961,0.12460,0.10960,0.2582,0.08893
125,B,13.85,17.21,88.44,588.7,0.08785,0.06136,0.01420,0.01141,0.1614,...,15.49,23.58,100.30,725.9,0.1157,0.1350,0.08115,0.05104,0.2364,0.07182

In [8]:
XTrain, XTest, yTrain, yTest = train_test_split(rawDataFrame.iloc[:,1:], rawDataFrame.iloc[:, 0], stratify=rawDataFrame.iloc[:, 0], test_size=0.2)
XTrain, XTest, yTrain, yTest

(     radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
 330       16.030         15.51          105.80      793.2          0.09491
 175        8.671         14.45           54.42      227.2          0.09138
 335       17.060         21.00          111.80      918.6          0.11190
 203       13.810         23.75           91.56      597.8          0.13230
 352       25.730         17.46          174.20     2010.0          0.11490
 ..           ...           ...             ...        ...              ...
 407       12.850         21.37           82.63      514.5          0.07551
 320       10.250         16.18           66.52      324.2          0.10610
 37        13.030         18.42           82.61      523.8          0.08983
 440       10.970         17.20           71.73      371.5          0.08915
 505        9.676         13.14           64.12      272.5          0.12550

      compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
 330           0.13710         0.12040              0.07041         0.1782
 175           0.04276         0.00000              0.00000         0.1722
 335           0.10560         0.15080              0.09934         0.1727
 203           0.17680         0.15580              0.09176         0.2251
 352           0.23630         0.33680              0.19130         0.1956
 ..                ...             ...                  ...            ...
 407           0.08316         0.06126              0.01867         0.1580
 320           0.11110         0.06726              0.03965         0.1743
 37            0.03766         0.02562              0.02923         0.1467
 440           0.11130         0.09457              0.03613         0.1489
 505           0.22040         0.11880              0.07038         0.2057

      fractal_dimension_mean  ...  radius_worst  texture_worst  \
 330                 0.05976  ...        18.760          21.98
 175                 0.06724  ...         9.262          17.04
 335                 0.06071  ...        20.990          33.15
 203                 0.07421  ...        19.200          41.85
 352                 0.06121  ...        33.130          23.58
 ..                      ...  ...           ...            ...
 407                 0.06114  ...        14.400          27.01
 320                 0.07279  ...        11.280          20.61
 37                  0.05863  ...        13.300          22.81
 440                 0.06640  ...        12.360          26.87
 505                 0.09575  ...        10.600          18.04

      perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
 330           124.30      1070.0           0.14350            0.44780
 175            58.36       259.2           0.11620            0.07057
 335           143.20      1362.0           0.14490            0.20530
 203           128.50      1153.0           0.22260            0.52090
 352           229.30      3234.0           0.15300            0.59370
 ..               ...         ...               ...                ...
 407            91.63       645.8           0.09402            0.19360
 320            71.53       390.4           0.14020            0.23600
 37             84.46       545.9           0.09701            0.04619
 440            90.14       476.4           0.13910            0.40820
 505            69.47       328.1           0.20060            0.36630

      concavity_worst  concave points_worst  symmetry_worst  \
 330          0.49560               0.19810          0.3019
 175          0.00000               0.00000          0.2592
 335          0.39200               0.18270          0.2623
 203          0.46460               0.20130          0.4432
 352          0.64510               0.27560          0.3690
 ..               ...                   ...             ...
 407          0.18380               0.05601          0.2488
 320          0.18980               0.09744          0.2608
 37           0.04833               0.05013          0.1987
 440          0.47790               0.15550          0.2540
 505          0.29130               0.10750          0.2848

      fractal_dimension_worst
 330                  0.09124
 175                  0.07848
 335                  0.07599
 203                  0.10860
 352                  0.08815
 ..                       ...
 407                  0.08151
 320                  0.09702
 37                   0.06169
 440                  0.09532
 505                  0.13640

 [455 rows x 30 columns],
      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
 255        13.96         17.05           91.43      602.4          0.10960
 370        16.35         23.29          109.00      840.4          0.09742
 458        13.00         25.13           82.61      520.2          0.08369
 408        17.99         20.66          117.80      991.7          0.10360
 285        12.58         18.40           79.83      489.0          0.08393
 ..           ...           ...             ...        ...              ...
 100        13.61         24.98           88.05      582.7          0.09488
 339        23.51         24.27          155.10     1747.0          0.10690
 256        19.55         28.77          133.60     1207.0          0.09260
 419        11.16         21.41           70.95      380.3          0.10180
 220        13.65         13.16           87.88      568.9          0.09646

      compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
 255           0.12790        0.097890             0.052460         0.1908
 370           0.14970        0.181100             0.087730         0.2175
 458           0.05073        0.012060             0.017620         0.1667
 408           0.13040        0.120100             0.088240         0.1992
 285           0.04216        0.001860             0.002924         0.1697
 ..                ...             ...                  ...            ...
 100           0.08511        0.086250             0.044890         0.1609
 339           0.12830        0.230800             0.141000         0.1797
 256           0.20630        0.178400             0.114400         0.1893
 419           0.05978        0.008955             0.010760         0.1615
 220           0.08711        0.038880             0.025630         0.1360

      fractal_dimension_mean  ...  radius_worst  texture_worst  \
 255                 0.06130  ...         16.39          22.07
 370                 0.06218  ...         19.38          31.03
 458                 0.05449  ...         14.34          31.88
 408                 0.06069  ...         21.08          25.41
 285                 0.05855  ...         13.50          23.08
 ..                      ...  ...           ...            ...
 100                 0.05871  ...         16.99          35.27
 339                 0.05506  ...         30.67          30.73
 256                 0.06232  ...         25.05          36.27
 419                 0.06144  ...         12.36          28.92
 220                 0.06344  ...         15.34          16.35

      perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
 255           108.10       826.0            0.1512            0.32620
 370           129.30      1165.0            0.1415            0.46650
 458            91.06       628.5            0.1218            0.10930
 408           138.10      1349.0            0.1482            0.37350
 285            85.56       564.1            0.1038            0.06624
 ..               ...         ...               ...                ...
 100           108.60       906.5            0.1265            0.19430
 339           202.40      2906.0            0.1515            0.26780
 256           178.60      1926.0            0.1281            0.53290
 419            79.26       458.0            0.1282            0.11080
 220            99.71       706.2            0.1311            0.24740

      concavity_worst  concave points_worst  symmetry_worst  \
 255         0.320900              0.137400          0.3068
 370         0.708700              0.224800          0.4824
 458         0.044620              0.059210          0.2306
 408         0.330100              0.197400          0.3060
 285         0.005579              0.008772          0.2505
 ..               ...                   ...             ...
 100         0.316900              0.118400          0.2651
 339         0.481900              0.208900          0.2593
 256         0.425100              0.194100          0.2818
 419         0.035820              0.043060          0.2976
 220         0.175900              0.080560          0.2380

      fractal_dimension_worst
 255                  0.07957
 370                  0.09614
 458                  0.06291
 408                  0.08503
 285                  0.06431
 ..                       ...
 100                  0.07397
 339                  0.07738
 256                  0.10050
 419                  0.07123
 220                  0.08718

 [114 rows x 30 columns],
 330    M
 175    B
 335    M
 203    M
 352    M
       ..
 407    B
 320    B
 37     B
 440    B
 505    B
 Name: diagnosis, Length: 455, dtype: str,
 255    M
 370    M
 458    B
 408    M
 285    B
       ..
 100    M
 339    M
 256    M
 419    B
 220    B
 Name: diagnosis, Length: 114, dtype: str)

In [9]:
rawDataFrame["diagnosis"].value_counts(normalize=True)

diagnosis
B    0.627417
M    0.372583
Name: proportion, dtype: float64

In [10]:
yTrain.value_counts(normalize=True)

diagnosis
B    0.626374
M    0.373626
Name: proportion, dtype: float64

In [11]:
encoder = LabelEncoder()
yTrain = encoder.fit_transform(yTrain)
yTest = encoder.fit_transform(yTest)
yTrain, yTest

(array([1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0]))

In [12]:
preprocessPipeline = Pipeline(
    [
        ("Scale", StandardScaler()),
        (
            "Impute",
            KNNImputer(
                n_neighbors=5,
                weights="distance",
                metric="nan_euclidean"
            )
        )
    ]
)

XTrain = preprocessPipeline.fit_transform(XTrain)
XTest = preprocessPipeline.transform(XTest)
XTrain, XTest

(array([[ 0.55987153, -0.85521762,  0.59126222, ...,  1.29368704,
          0.16799011,  0.40890388],
        [-1.54207613, -1.10684428, -1.54283933, ..., -1.78105409,
         -0.53052156, -0.3139355 ],
        [ 0.85406994,  0.44801858,  0.8404761 , ...,  1.05466123,
         -0.47980994, -0.45499114],
        ...,
        [-0.29701704, -0.16443121, -0.37194944, ..., -1.00297851,
         -1.52021608, -1.26506975],
        [-0.88541385, -0.45403926, -0.82385728, ...,  0.63248577,
         -0.61558622,  0.6400312 ],
        [-1.25501846, -1.41781685, -1.13994355, ..., -0.11252975,
         -0.11174173,  2.96716611]], shape=(455, 30)),
 array([[-0.03138158, -0.48964681, -0.00560503, ...,  0.35155283,
          0.24814718, -0.25218825],
        [ 0.65127298,  0.99162713,  0.72417629, ...,  1.70810193,
          3.12071508,  0.68648326],
        [-0.30558592,  1.42841303, -0.37194944, ..., -0.86204641,
         -0.99837715, -1.19595815],
        ...,
        [ 1.56528745,  2.29248949,  1.74595321, ...,  1.23160242,
         -0.16081749,  0.93347226],
        [-0.83114425,  0.54534588, -0.85625508, ..., -1.11271309,
          0.09764818, -0.72463969],
        [-0.11992673, -1.41306918, -0.15305658, ..., -0.53066971,
         -0.87732361,  0.17890953]], shape=(114, 30)))

In [13]:
XTrain = torch.from_numpy(XTrain)
XTest = torch.from_numpy(XTest)
yTrain = torch.from_numpy(yTrain)
yTest = torch.from_numpy(yTest)
XTrain, XTest, yTrain, yTest

(tensor([[ 0.5599, -0.8552,  0.5913,  ...,  1.2937,  0.1680,  0.4089],
         [-1.5421, -1.1068, -1.5428,  ..., -1.7811, -0.5305, -0.3139],
         [ 0.8541,  0.4480,  0.8405,  ...,  1.0547, -0.4798, -0.4550],
         ...,
         [-0.2970, -0.1644, -0.3719,  ..., -1.0030, -1.5202, -1.2651],
         [-0.8854, -0.4540, -0.8239,  ...,  0.6325, -0.6156,  0.6400],
         [-1.2550, -1.4178, -1.1399,  ..., -0.1125, -0.1117,  2.9672]],
        dtype=torch.float64),
 tensor([[-0.0314, -0.4896, -0.0056,  ...,  0.3516,  0.2481, -0.2522],
         [ 0.6513,  0.9916,  0.7242,  ...,  1.7081,  3.1207,  0.6865],
         [-0.3056,  1.4284, -0.3719,  ..., -0.8620, -0.9984, -1.1960],
         ...,
         [ 1.5653,  2.2925,  1.7460,  ...,  1.2316, -0.1608,  0.9335],
         [-0.8311,  0.5453, -0.8563,  ..., -1.1127,  0.0976, -0.7246],
         [-0.1199, -1.4131, -0.1531,  ..., -0.5307, -0.8773,  0.1789]],
        dtype=torch.float64),
 tensor([1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
         0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
         0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
         0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
         1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
         0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
         1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
         0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
         1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
         1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
         1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
         0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
         0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]),
 tensor([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
         1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
         0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
         1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
         1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0]))

In [14]:
XTrain.shape

torch.Size([455, 30])

In [15]:
yTrain = yTrain.reshape(-1, 1)
yTest = yTest.reshape(-1, 1)
yTest[0:20]

tensor([[1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1]])

# With Single perceptron

In [16]:
torch.manual_seed(67)
class SingleN():
    def __init__(self, X):
        self.w = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.b = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    
    def forwardPropagation(self, X):
        z = torch.matmul(X, self.w) + self.b
        return torch.sigmoid(z)
    
    def lossFunction(self, y, yHat):
        e = 1e-16
        yHat = yHat.clamp(e, (1 - e))
        loss = -((y * yHat.log()) + ((1 - y) * torch.log(1-yHat)))
        return loss.mean()

In [17]:
epochs = 30_000
alpha = 0.003
model = SingleN(XTrain)

for epoch in range(epochs):

    with torch.no_grad():
        yEvalHat = model.forwardPropagation(XTest)
        lossOnEval = model.lossFunction(yTest, yEvalHat)
        yEvalHat = (yEvalHat > 0.5).int()
        evalAccuracy = (yTest == yEvalHat).float().mean()

    yHat = model.forwardPropagation(XTrain)
    loss = model.lossFunction(yTrain, yHat)

    loss.backward()

    with torch.no_grad():
        model.w -= alpha * model.w.grad
        model.b -= alpha * model.b.grad
    
    model.w.grad.zero_()
    model.b.grad.zero_()

    if((epoch+1) % 3_000 == 0):
        with torch.no_grad():
            yHat = (yHat > 0.5).int()
            trainAccuracy = (yTrain == yHat).float().mean()
            print(f"Epoch: {epoch + 1}, train loss: {loss}, train accuracy: {trainAccuracy*100}% | evaluation loss: {lossOnEval}, evaluation accuracy: {evalAccuracy*100}%")

Epoch: 3000, train loss: 0.06742074380309748, train accuracy: 97.36264038085938% | evaluation loss: 0.19493112681309546, evaluation accuracy: 92.98246002197266%
Epoch: 6000, train loss: 0.05582473470663926, train accuracy: 98.02198028564453% | evaluation loss: 0.18663447334377606, evaluation accuracy: 92.98246002197266%
Epoch: 9000, train loss: 0.051615835433762566, train accuracy: 98.24176025390625% | evaluation loss: 0.1856915237083035, evaluation accuracy: 92.98246002197266%
Epoch: 12000, train loss: 0.04893198658617699, train accuracy: 98.46154022216797% | evaluation loss: 0.18639115654757066, evaluation accuracy: 93.85964965820312%
Epoch: 15000, train loss: 0.04696689193311293, train accuracy: 98.46154022216797% | evaluation loss: 0.1876272732783938, evaluation accuracy: 93.85964965820312%
Epoch: 18000, train loss: 0.04543073551053747, train accuracy: 98.46154022216797% | evaluation loss: 0.18905682788895642, evaluation accuracy: 93.85964965820312%
Epoch: 21000, train loss: 0.04417939853633717, train accuracy: 98.68132019042969% | evaluation loss: 0.19055337033417627, evaluation accuracy: 93.85964965820312%
Epoch: 24000, train loss: 0.04312896771872969, train accuracy: 98.68132019042969% | evaluation loss: 0.19206677094596894, evaluation accuracy: 93.85964965820312%
Epoch: 27000, train loss: 0.042226228510225235, train accuracy: 98.68132019042969% | evaluation loss: 0.19357687423986036, evaluation accuracy: 93.85964965820312%
Epoch: 30000, train loss: 0.04143567720727627, train accuracy: 98.68132019042969% | evaluation loss: 0.1950757669334429, evaluation accuracy: 93.85964965820312%

# With MLP

In [18]:
class NeuralN:
    def __init__(self, X):

        input_features = X.shape[1]

        # He initialization for ReLU layers
        self.w1 = (
            torch.randn(input_features, 10, dtype=torch.float64)
            * (2 / input_features) ** 0.5
        ).requires_grad_()
        self.b1 = torch.zeros(10, dtype=torch.float64, requires_grad=True)

        self.w2 = (
            torch.randn(10, 7, dtype=torch.float64)
            * (2 / 10) ** 0.5
        ).requires_grad_()
        self.b2 = torch.zeros(7, dtype=torch.float64, requires_grad=True)

        self.w3 = (
            torch.randn(7, 4, dtype=torch.float64)
            * (2 / 7) ** 0.5
        ).requires_grad_()
        self.b3 = torch.zeros(4, dtype=torch.float64, requires_grad=True)

        # Output layer
        self.w4 = (
            torch.randn(4, 1, dtype=torch.float64)
            * (2 / 4) ** 0.5
        ).requires_grad_()
        self.b4 = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forwardPropagation(self, X):

        # Layer 1
        z1 = torch.matmul(X, self.w1) + self.b1
        a1 = torch.relu(z1)

        # Layer 2
        z2 = torch.matmul(a1, self.w2) + self.b2
        a2 = torch.relu(z2)

        # Layer 3
        z3 = torch.matmul(a2, self.w3) + self.b3
        a3 = torch.relu(z3)

        # Output layer
        z4 = torch.matmul(a3, self.w4) + self.b4
        yHat = torch.sigmoid(z4)

        return yHat

    def lossFunction(self, y, yHat):

        e = 1e-16

        yHat = yHat.clamp(e, 1 - e)

        loss = (
            -(y * torch.log(yHat))
            - ((1 - y) * torch.log(1 - yHat))
        )

        return loss.mean()

In [25]:
epochs = 20_00_000
alpha = 0.000001

model = NeuralN(XTrain)

for epoch in range(epochs):

    # Clear previous gradients
    if model.w1.grad is not None:
        model.w1.grad.zero_()
        model.b1.grad.zero_()
        model.w2.grad.zero_()
        model.b2.grad.zero_()
        model.w3.grad.zero_()
        model.b3.grad.zero_()
        model.w4.grad.zero_()
        model.b4.grad.zero_()

    # Training forward propagation
    yHat = model.forwardPropagation(XTrain)

    # Training loss
    loss = model.lossFunction(yTrain, yHat)

    # Backpropagation
    loss.backward()

    # Gradient descent
    with torch.no_grad():
        model.w1 -= alpha * model.w1.grad
        model.b1 -= alpha * model.b1.grad

        model.w2 -= alpha * model.w2.grad
        model.b2 -= alpha * model.b2.grad

        model.w3 -= alpha * model.w3.grad
        model.b3 -= alpha * model.b3.grad

        model.w4 -= alpha * model.w4.grad
        model.b4 -= alpha * model.b4.grad

    

    # Logging
    if (epoch + 1) % 1_00_000 == 0:

        # Evaluation
        with torch.no_grad():

            yEvalHat = model.forwardPropagation(XTest)

            lossOnEval = model.lossFunction(
                yTest,
                yEvalHat
            )

            evalPrediction = (yEvalHat > 0.5).int()
            evalAccuracy = (
                (yTest == evalPrediction)
                .float()
                .mean()
            )

        with torch.no_grad():

            trainPrediction = (yHat > 0.5).int()

            trainAccuracy = (
                (yTrain == trainPrediction)
                .float()
                .mean()
            )

            print(
                f"Epoch: {epoch + 1}, "
                f"train loss: {loss.item()}, "
                f"train accuracy: {trainAccuracy.item() * 100:.2f}% | "
                f"evaluation loss: {lossOnEval.item()}, "
                f"evaluation accuracy: {evalAccuracy.item() * 100:.2f}%"
            )

Epoch: 100000, train loss: 0.5603276221189725, train accuracy: 68.57% | evaluation loss: 0.5818046794720705, evaluation accuracy: 71.05%
Epoch: 200000, train loss: 0.5037464476333108, train accuracy: 79.12% | evaluation loss: 0.5227746568143364, evaluation accuracy: 79.82%
Epoch: 300000, train loss: 0.46723295408658555, train accuracy: 83.30% | evaluation loss: 0.4844053464861005, evaluation accuracy: 84.21%
Epoch: 400000, train loss: 0.4366520715987178, train accuracy: 87.69% | evaluation loss: 0.4528140292357544, evaluation accuracy: 85.09%
Epoch: 500000, train loss: 0.40939659343802753, train accuracy: 88.13% | evaluation loss: 0.4247075878456076, evaluation accuracy: 85.09%
Epoch: 600000, train loss: 0.3851700659692158, train accuracy: 90.11% | evaluation loss: 0.3993057530122392, evaluation accuracy: 87.72%
Epoch: 700000, train loss: 0.36259863556641675, train accuracy: 90.77% | evaluation loss: 0.37576561732732894, evaluation accuracy: 90.35%
Epoch: 800000, train loss: 0.34094409445721674, train accuracy: 91.43% | evaluation loss: 0.3535321389143275, evaluation accuracy: 91.23%
Epoch: 900000, train loss: 0.32030262131626547, train accuracy: 92.31% | evaluation loss: 0.33286578588065563, evaluation accuracy: 93.86%
Epoch: 1000000, train loss: 0.3007713052549413, train accuracy: 93.41% | evaluation loss: 0.31376973778815404, evaluation accuracy: 93.86%
Epoch: 1100000, train loss: 0.28256287246107115, train accuracy: 93.85% | evaluation loss: 0.2962799755733245, evaluation accuracy: 95.61%
Epoch: 1200000, train loss: 0.2656754417163337, train accuracy: 93.85% | evaluation loss: 0.28066962586922695, evaluation accuracy: 95.61%
Epoch: 1300000, train loss: 0.25029306531862516, train accuracy: 94.51% | evaluation loss: 0.26687074961059154, evaluation accuracy: 95.61%
Epoch: 1400000, train loss: 0.23645838301399094, train accuracy: 94.51% | evaluation loss: 0.2546828007885802, evaluation accuracy: 95.61%
Epoch: 1500000, train loss: 0.22384412091226447, train accuracy: 94.73% | evaluation loss: 0.24405372245572146, evaluation accuracy: 95.61%
Epoch: 1600000, train loss: 0.21247427300364471, train accuracy: 94.95% | evaluation loss: 0.23479532597030098, evaluation accuracy: 94.74%
Epoch: 1700000, train loss: 0.2021405915805255, train accuracy: 95.16% | evaluation loss: 0.2265808501442138, evaluation accuracy: 94.74%
Epoch: 1800000, train loss: 0.19282488317877386, train accuracy: 95.38% | evaluation loss: 0.2193451229339926, evaluation accuracy: 94.74%
Epoch: 1900000, train loss: 0.1843514803336073, train accuracy: 95.38% | evaluation loss: 0.21298412856151372, evaluation accuracy: 94.74%
Epoch: 2000000, train loss: 0.17666548621237899, train accuracy: 95.38% | evaluation loss: 0.20740105811227907, evaluation accuracy: 95.61%

In [26]:
print("Class ratio:", yTrain.float().mean().item())

with torch.no_grad():
    yHat = model.forwardPropagation(XTrain)
    yPred = (yHat > 0.5).int()

    print("Predicted positive ratio:", yPred.float().mean().item())
    print("Train loss:", loss.item())
    print("Accuracy:", ((yTrain == yPred).float().mean().item()))

Class ratio: 0.37362638115882874
Predicted positive ratio: 0.35384616255760193
Train loss: 0.17666548621237899
Accuracy: 0.9538461565971375

In [27]:
with torch.no_grad():
    z1 = torch.matmul(XTrain, model.w1) + model.b1
    a1 = torch.relu(z1)

    z2 = torch.matmul(a1, model.w2) + model.b2
    a2 = torch.relu(z2)

    z3 = torch.matmul(a2, model.w3) + model.b3
    a3 = torch.relu(z3)

    z4 = torch.matmul(a3, model.w4) + model.b4
    yHat = torch.sigmoid(z4)

    print("a1 positive:", (a1 > 0).float().mean().item())
    print("a2 positive:", (a2 > 0).float().mean().item())
    print("a3 positive:", (a3 > 0).float().mean().item())

    print("yHat mean:", yHat.mean().item())
    print("yHat min :", yHat.min().item())
    print("yHat max :", yHat.max().item())

    print("b1:", model.b1)
    print("b2:", model.b2)
    print("b3:", model.b3)
    print("b4:", model.b4)

a1 positive: 0.5248351693153381
a2 positive: 0.5729984045028687
a3 positive: 0.6708791255950928
yHat mean: 0.3545401808113231
yHat min : 1.66180966982416e-05
yHat max : 0.997457079224999
b1: tensor([ 0.0268,  0.0471, -0.0454, -0.0475,  0.0307,  0.0093,  0.1074,  0.0138,
        -0.0060,  0.0516], dtype=torch.float64, requires_grad=True)
b2: tensor([-0.0021,  0.0032,  0.1050, -0.0058,  0.0784, -0.0130, -0.0052],
       dtype=torch.float64, requires_grad=True)
b3: tensor([ 0.0383,  0.0407, -0.0157,  0.1220], dtype=torch.float64,
       requires_grad=True)
b4: tensor([0.0709], dtype=torch.float64, requires_grad=True)

In [28]:
with torch.no_grad():
    z1 = XTrain @ model.w1 + model.b1
    a1 = torch.relu(z1)

    z2 = a1 @ model.w2 + model.b2
    a2 = torch.relu(z2)

    z3 = a2 @ model.w3 + model.b3
    a3 = torch.relu(z3)

    z4 = a3 @ model.w4 + model.b4

    print("z4 mean:", z4.mean().item())
    print("z4 std :", z4.std().item())

z4 mean: -1.4825947882063981
z4 std : 2.96555257668311

In [29]:
print("XTrain:", XTrain.shape)
print("yTrain:", yTrain.shape)

with torch.no_grad():
    yHat = model.forwardPropagation(XTrain)
    print("yHat:", yHat.shape)

XTrain: torch.Size([455, 30])
yTrain: torch.Size([455, 1])
yHat: torch.Size([455, 1])